spring:
  application:
    name:
      company
  h2:
    console:
      enabled:
        true
  datasource:
    url:
      jdbc:h2:mem:company
    driverClassName:
      org.h2.Driver
  jpa:
    database-platform:
      org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto:
      validate
    show-sql:
      true

logging:
  level:
    org:
      springframework:
        web:
          DEBUG
    hibernate:
      ERROR