CREATE TABLE USER_LOGIN
(
    ID       BIGINT PRIMARY KEY,
    NAME     VARCHAR(50)  NOT NULL,
    EMAIL    VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE DEPARTMENT
(
    ID        BIGINT PRIMARY KEY,
    NAME      VARCHAR(50) NOT NULL UNIQUE,
    MANDATORY BOOLEAN NOT NULL,
    READ_ONLY BOOLEAN NOT NULL
);

CREATE TABLE EMPLOYEE
(
    ID   BIGINT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE MAP_EMPLOYEE_DEPARTMENT
(
    ID_EMPLOYEE   BIGINT NOT NULL,
    ID_DEPARTMENT BIGINT NOT NULL,
    PRIMARY KEY (ID_EMPLOYEE, ID_DEPARTMENT),
    CONSTRAINT FK_EMPLOYEE_EMPLOYEE_DEPARTMENT FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE (ID),
    CONSTRAINT FK_DEPARTMENT_EMPLOYEE_DEPARTMENT FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENT (ID)
);

CREATE SEQUENCE SEQUENCE_DEPARTMENT START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQUENCE_EMPLOYEE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQUENCE_USER START WITH 1 INCREMENT BY 1;


